function jsnavigatorsuite() {
  var testSuite = new top.jsUnitTestSuite();
  testSuite.addTestPage("../tests/js/navigator/navigator-appMinorVersion-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-appName-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-appVersion-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-browserLanguage-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-buildID-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-cookieEnabled-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-cpuClass-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-javaEnabled-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-language-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-mimeTypes-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-onLine-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-oscpu-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-platform-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-plugins-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-product-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-productSub-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-registerContentHandler-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-registerProtocolHandler-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-securityPolicy-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-systemLanguage-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-taintEnabled-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-userAgent-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-userLanguage-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-userProfile-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-vendor-typeof-test.html");
  testSuite.addTestPage("../tests/js/navigator/navigator-vendorSub-typeof-test.html");
  return testSuite;
}
